// const MODEL = require('../../../models/mongo/role.js');

// function initializeRole() {
//     return new Promise((resolve, reject) => {
//         const data = [
//             {
//                 name: 'Super Admin',
//                 code: 'SUPERADMIN',
//                 description: 'This is admin',
//                 is_active: true,
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 created_at: new Date(),
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         USER: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         ROLE: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         PRODUCT: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         STUDIO: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         STUDIOCATEGORY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         LOCATION: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         COMPANY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//             },
//             {
//                 name: 'Product Manager',
//                 code: 'PRODUCTMANAGER',
//                 description: 'This is Product  manager',
//                 is_active: true,
//                 created_at: new Date(),
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//             },
//             {
//                 code: 'PREPRODUCTIONMANAGER',
//                 name: 'Pre Production Manager',
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         SCRIPT_QC: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 created_at: new Date(),
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             {
//                 created_at: new Date(),
//                 code: 'SCRIPTWRITER',
//                 name: 'Scriptwriter',
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             /* 5 */
//             {
//                 created_at: new Date(),
//                 code: 'PRODUCTIONMANAGER',
//                 name: 'Production Manager',
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             /* 6 */
//             {
//                 created_at: new Date(),
//                 createdBy: {
//                     id: '1',
//                     name: 'Admin',
//                 },
//                 code: 'ASSISTANTDIRECTOR',
//                 name: 'Assistant Director',
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             /* 7 */
//             {
//                 created_at: new Date(),
//                 createdBy: {
//                     id: '1',
//                     name: 'Admin',
//                 },
//                 code: 'POSTPRODUCTIONSUPERVISOR',
//                 name: 'Post Production SuperVisor',
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             /* 8 */
//             {
//                 created_at: new Date(),
//                 createdBy: {
//                     id: '1',
//                     name: 'Admin',
//                 },
//                 code: 'EDITOR',
//                 name: 'Editor',
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             /* 9 */
//             {
//                 created_at: new Date(),
//                 code: 'QCER',
//                 name: 'Qcer',
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             /* 10 */
//             {
//                 created_at: new Date(),
//                 createdBy: {
//                     id: '1',
//                     name: 'Admin',
//                 },
//                 code: 'FINALASSIGNER',
//                 name: 'Final Assigner',
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: true,
//                             add: true,
//                             edit: true,
//                             delete: true,
//                         },
//                     },
//                 ],
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 updated_by: {
//                     id: '',
//                     name: '',
//                 },
//                 is_active: true,
//                 __v: 0,
//             },
//             {
//                 name: 'Influencer',
//                 code: 'INFLUENCER',
//                 description: 'This is infulencer',
//                 is_active: true,
//                 created_by: {
//                     id: 'system',
//                     name: 'System',
//                 },
//                 created_at: new Date(),
//                 assign_role: [
//                     {
//                         DASHBOARD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         USER: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ROLE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIO: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         STUDIOCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         LOCATION: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         PRODUCTSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         VIDEOFORMATSUBCATEGORY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         TOPIC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_SCRIPT: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_FOOTAGE: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_UPLOAD: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         FINAL_FOOTAGE_QC: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                         ASSIGN_COMPANY: {
//                             view: false,
//                             add: false,
//                             edit: false,
//                             delete: false,
//                         },
//                     },
//                 ],
//             },
//         ];
//         // CHECKS WHETHER THE COLLECTION IS EMPTY , IF YES THEN INITIALIZE IT
//         MODEL.count().then((count) => {
//             if (count === 0) {
//                 console.log('### INITIALIZE ADMIN ROLE RECORDS ###');
//                 MODEL.insertMany(data).then((response) => {
//                     resolve(response);
//                 }).catch((err) => {
//                     reject(err);
//                 });
//             } else {
//                 console.log('### ROLE ALREADY INITIALIZED! ###');
//                 resolve(count);
//             }
//         }).catch((err) => {
//             reject(err);
//         });
//     });
// }

// module.exports = {
//     initializeRole,
// };
